id: trigger_flow
namespace: example
description: Trigger a flow once another flow is finished successfully

inputs:
  - id: from-parent
    type: STRING

tasks:
  - id: print_input
    type: io.kestra.plugin.core.debug.Return
    format: "children: {{inputs['from-parent']}}"

triggers:
  - id: listen-flow
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      from-parent: '{{ outputs.only.value }}'
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: io.kestra.demo
        flowId: multiplecondition-flow-a
