id: trigger_flow
namespace: dev
description: Trigger a flow once another flow is finished successfully

inputs:
  - id: from-parent
    type: STRING

tasks:
  - id: print_input
    type: io.kestra.core.tasks.debugs.Return
    format: "childs: {{inputs['from-parent']}}"

triggers:
  - id: listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    inputs:
      from-parent: '{{ outputs.only.value }}'
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: io.kestra.demo
        flowId: multiplecondition-flow-a
