id: trigger_flow
namespace: company.team
description: Trigger a flow once another flow is finished successfully

inputs:
  - id: from_parent
    type: STRING

tasks:
  - id: print_input
    type: io.kestra.plugin.core.debug.Return
    format: "children: {{inputs['from-parent']}}"

triggers:
  - id: listen_flow
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      from-parent: '{{ outputs.only.value }}'
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: company.team
        flowId: multiplecondition_flow_a
