name: Bug on the website
description: File a bug report for something that doesn't look right on the website.
body:
  - type: markdown
    attributes:
      value: |
        This template is for filing bugs on the website. If you want to report something in the docs content, please use the [documentation issue template](https://github.com/kestra-io/docs/issues/new?assignees=&labels=documentation&projects=&template=documentation.yml).
        Attach screenshot images or a screen-capture video to help us reproduce and fix the issue.
        NOTE: If your issue is more of a question, ping us directly on [Slack](https://kestra.io/slack).
  - type: textarea
    attributes:
      label: Describe the issue
      description: Description of the issue and how we can reproduce it.
      placeholder: Describe the issue, add any screenshots or screen-capture videos.
    validations:
      required: true
labels:
  - area/frontend
  - bug