contact_links:
  - name: GitHub Discussions
    url: https://github.com/kestra-io/kestra/discussions
    about: Ask questions about Kestra on GitHub
  - name: Chat
    url: https://kestra.io/slack
    about: Chat with us on Slack.