name: Documentation Issue
description: Create a new documentation issue
body:
  - type: textarea
    attributes:
      label: Describe what's missing in our docs
      placeholder: Describe anything that's missing or incorrect in our documentation
    validations:
      required: true
labels:
  - area/docs
