name: Documentation Issue
description: Create a new documentation issue
body:
  - type: markdown
    attributes:
      value: |
        Please describe what did you find missing in the documentation and what you would like to see added.
  - type: textarea
    attributes:
      label: Description
      placeholder: Describe the issue concisely
    validations:
      required: true
labels:
  - documentation
