// @ts-check

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import figma from "./Figma.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const AUTO_GENERATED_COMMENT = `/**
 * This file is auto-generated by scripts/generate-palette.mjs. 
 * It is a summary of color choices made in Figma.
 * Should you need to make a change in it, ask a designer 
 * at Kestra first, so your changes are not overwritten. 
 */`;

const [{ color: paletteLight }, { color: paletteDark }] = figma[1].values;

/**
 * @param {Array<{name: string, value: string}>} palette1
 * @param {Array<{name: string, value: string}>} palette2
 */
const checkPalette = (palette1, palette2) => {
    for (const color1 of palette1) {
        const color2 = palette2.find((c) => c.name === color1.name);
        if (!color2 || color2.value !== color1.value) {
            console.error(`Color ${color1.name} is different in the two palettes`);
        }
    }
};

/**
 * @param {{var?: string, value: string}} color
 * @param {Record<string, string>} colorIndex
 */
const getValue = (color, colorIndex) => {
    // If it's a reference to a base color (grey/ or primary/)
    if (color.var?.match(/^(grey|primary)\//)) {
        return `$base-${color.var.replace(/\//g, "-")}`;
    }

    // if the value of the color has 8 hexadecimal it has an alpha channel
    // we therefore extract the color and compare it with the values in the base palette
    if (color.value.length === 9) {
        const alpha = Math.round(parseInt(color.value.slice(7), 16) / 2.55) / 100;
        const baseColor = color.value.slice(0, 7);
        const baseColorName = colorIndex[baseColor];
        if (baseColorName) {
            return `rgba($base-${baseColorName.replace(/\//g, "-")}, ${alpha})`;
        }
    }
    return color.value;
};

/**
 * @param {Array<{name: string, value: string}>} themeColors
 * @param {Record<string, string>} colorIndex
 */
const getVariableScss = (themeColors, colorIndex) => {
    /** @type {string | null} */
    let prevCategory = null;

    return themeColors
        .map((c) => {
            const currentCategory = c.name.replace(/^ks\//, "").split("-")[0];
            const val = getValue(c, colorIndex);
            const categoryTitle =
                currentCategory !== prevCategory
                    ? `\n\t/* ${currentCategory} */\n`
                    : "";
            
            const varName = c.name.replace(/\//g, "-");
            prevCategory = currentCategory;
            
            return `${categoryTitle}\t#{--${varName}}: ${val};`;
        })
        .join("\n")
        .trim();
};

/**
 * @param {Array<{name: string, value: string}>} palette
 * @param {string} paletteName
 * @param {string} selector
 */
const makePalettes = (palette, paletteName, selector) => {
    // Base colors are grey/ or primary/
    const baseColors = palette
        .filter((c) => c.name.match(/^(grey|primary)\//))
        .sort((a, b) => a.name.localeCompare(b.name));

    const colorIndex = baseColors.reduce(
        (acc, color) => ({ ...acc, [color.value]: color.name }),
        {}
    );

    const scss = baseColors
        .map((color) => `$base-${color.name.replace(/\//g, "-")}: ${color.value};`)
        .join("\n");

    // write the scss file containing colors in the base palette
    fs.writeFileSync(
        path.resolve(__dirname, "../src/assets/styles/_color-palette.scss"),
        `${AUTO_GENERATED_COMMENT}\n${scss}`,
        { encoding: "utf-8" }
    );

    const tokenScss = getVariableScss(
        palette.filter((c) => !c.name.match(/^(grey|primary)\//)),
        colorIndex
    );

    // write the scss file containing colors in the token palette
    fs.writeFileSync(
        path.resolve(
            __dirname,
            `../src/assets/styles/ks-theme-${paletteName}.scss`
        ),
        `${AUTO_GENERATED_COMMENT}\n@import "./color-palette.scss";\n\n${selector}{\n\t${tokenScss}\n}`,
        { encoding: "utf-8" }
    );

    return baseColors;
};

const colorLight = makePalettes(paletteLight, "light", ":root");
const colorDark = makePalettes(paletteDark, "dark", "html.dark");

checkPalette(colorLight, colorDark);
checkPalette(colorDark, colorLight);
